name: build-act
on: [workflow_dispatch]  # manual 
jobs:
  main:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo ciao
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist-without-markdown
          path: |
            dist
            !dist/**/*.md
      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: output/test/code-coverage.html
