name: build-act
on: [workflow_dispatch]  # manual trigger 
jobs:
  main:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2  # checkout repo in VM  
      - run: |  # Log  virtenv 
          cd    > build-artifact.txt # D:\a\reponame\reponame or %GITHUB_WORKSPACE% or %RUNNER_WORKSPACE%\reponame
          set  >> build-artifact.txt
          Rscript --version >> build-artifact.txt
          dir  >> build-artifact.txt
          dir  %RUNNER_WORKSPACE% >> build-artifact.txt
          dir  %RUNNER_WORKSPACE%\..     >> build-artifact.txt # D:\a\
          dir  %RUNNER_WORKSPACE%\.. \.. >> build-artifact.txt # D:\
          
        shell: cmd

      ##  Upload in github the file generated
      - uses: actions/upload-artifact@v2
        with:
          name: build-artifact
          path: build-artifact.txt
          retention-days: 1

