name: build-act
on: [workflow_dispatch]  # manual trigger 
jobs:
  main:
    runs-on: windows-latest
    steps:
      # - uses: actions/checkout@v2  # checkout repo in VM  
      - run: |  # Log  virtenv 
          $PSDefaultParameterValues['*:Encoding'] = 'utf8'
          pwd     > build-artifact.txt         
          ls env: >> build-artifact.txt
          $R=(dir $env:ProgramFiles\R).Name
          & $env:ProgramFiles\R\$R\bin\Rscript --version 2>&1 >> build-artifact.txt          

        shell: powershell

      ##  Upload in github the file generated
      - uses: actions/upload-artifact@v2
        with:
          name: build-artifact
          path: build-artifact.txt
          retention-days: 1


      
